export const portfolioSeed = {
  zh: {
    brandName: "李慧",
    brandRole: "高级前端工程师 / Frontend Engineer",
    nav: [
      { href: "#about", label: "关于" },
      { href: "#insight", label: "视角" },
      { href: "#achievement", label: "成果" },
      { href: "#capability", label: "能力" },
      { href: "#tooling", label: "技术" },
      { href: "#experience", label: "经历" },
      { href: "#projects", label: "项目" },
      { href: "#process", label: "方法" },
      { href: "#contact", label: "联系" },
    ],
    hero: {
      eyebrow: "PORTFOLIO 2026",
      title: "以设计品质与工程确定性，交付可持续增长的前端系统",
      lead:
        "8 年前端开发经验，长期服务教育、电商、协同平台和企业中后台。擅长从业务目标拆解、设计系统抽象到工程化落地的全链路推进，平衡用户体验、开发效率与长期可维护性。",
      primaryAction: "查看代表项目",
      secondaryAction: "发起沟通",
      badges: ["Vue / React", "Design System", "性能治理", "工程提效", "跨团队协作"],
      sideTitle: "Design x Engineering",
      sideDescription:
        "不只关注页面实现，更关注业务转化路径、研发协作效率与系统演进成本，持续将复杂需求转化为稳定可迭代的产品能力。",
    },
    metrics: [
      { label: "行业经验", value: "8+ 年" },
      { label: "主导项目", value: "20+" },
      { label: "影响团队", value: "4+ 职能协作" },
      { label: "资源优化", value: "最高降耗 70%" },
    ],
    sections: {
      insight: {
        eyebrow: "INSIGHTS",
        title: "职业视角与工作信条",
        description: "清晰的问题定义、可持续的工程实践与一致的体验标准，是我长期坚持的三条主线。",
      },
      achievement: {
        eyebrow: "ACHIEVEMENTS",
        title: "关键成果与业务价值",
        description: "围绕效率、质量、性能与交付稳定性，持续输出可量化成果。",
      },
      capability: {
        eyebrow: "CAPABILITY",
        title: "核心能力矩阵",
        description: "从产品体验到工程体系，形成端到端的专业交付能力。",
      },
      tooling: {
        eyebrow: "STACK",
        title: "技术深度与工程实践",
        description: "技术选型关注长期可维护性，实践强调标准化、自动化与可观测性。",
      },
      experience: {
        eyebrow: "EXPERIENCE",
        title: "职业经历",
        description: "在真实复杂业务中沉淀方法论，推动团队交付质量持续提升。",
      },
      projects: {
        eyebrow: "PROJECTS",
        title: "代表项目案例",
        description: "按“挑战-策略-结果”展开，展示完整的问题解决与价值交付链路。",
      },
      process: {
        eyebrow: "WORKFLOW",
        title: "工作方法",
        description: "统一产品目标、设计语言与代码实现，减少沟通损耗并提升交付效率。",
      },
      contact: {
        eyebrow: "CONTACT",
        title: "期待合作",
        description: "欢迎交流前端岗位、顾问合作、复杂系统重构与效率提升项目。",
      },
    },
    insight: {
      statement:
        "我相信优秀的前端不是“把页面写出来”，而是用系统化方式把业务、设计与工程协同起来，让产品长期保持可演进性。",
      nowTitle: "当前关注",
      nowItems: [
        "复杂业务系统的前端架构升级与模块治理",
        "设计系统在多团队场景下的标准化落地",
        "面向真实业务指标的性能优化闭环",
      ],
      principleTitle: "工作原则",
      principleItems: ["先定义问题，再设计方案", "面向复用抽象，而非一次性实现", "用数据验证优化效果，减少主观决策"],
    },
    achievements: [
      {
        value: "-35%",
        label: "平均迭代交付周期",
        detail: "通过需求拆解模板、组件复用策略和发布流程优化，显著缩短从评审到上线的端到端周期。",
      },
      {
        value: "70%",
        label: "资源成本下降峰值",
        detail: "推动构建链路升级、静态资源分层缓存与按需加载，降低网络与构建资源消耗。",
      },
      {
        value: "99.9%",
        label: "核心流程稳定性",
        detail: "建立异常分级、性能监控与回归保障机制，持续提升线上可用性与问题响应效率。",
      },
      {
        value: "1 套",
        label: "设计系统规范体系",
        detail: "落地设计 Token、组件规范和页面模板，统一视觉语言并减少跨项目重复建设。",
      },
    ],
    businessShowcase: {
      eyebrow: "BUSINESS IMPACT",
      title: "业务问题解决能力",
      description: "用“问题定义—决策路径—结果验证”的方式推动复杂业务落地，持续交付可量化价值。",
      anchors: [
        {
          label: "需求到上线周期",
          value: "-35%",
          detail: "通过模板化拆解与优先级机制，压缩跨团队等待时间。",
        },
        {
          label: "关键流程稳定性",
          value: "99.9%",
          detail: "将异常分级、灰度策略与回滚预案纳入标准发布流。",
        },
        {
          label: "跨团队协同效率",
          value: "+40%",
          detail: "统一评审与交付语言，降低沟通损耗与返工率。",
        },
      ],
      playbookTitle: "业务推进方法",
      playbook: [
        {
          title: "1. 锁定关键业务问题",
          description: "先识别影响营收、转化或效率的关键瓶颈，明确优先级和边界。",
          outcome: "目标一致，避免资源分散",
        },
        {
          title: "2. 建立可执行方案",
          description: "把业务目标拆成可交付模块，定义里程碑、风险清单和依赖关系。",
          outcome: "方案可落地，节奏可预测",
        },
        {
          title: "3. 按指标闭环迭代",
          description: "上线后跟踪核心指标与用户反馈，按证据持续优化而非拍脑袋。",
          outcome: "价值可验证，可持续增长",
        },
      ],
      casesTitle: "业务案例拆解",
      cases: [
        {
          scenario: "活动页大促转化波动",
          metric: "转化率 +22%",
          challenge: "活动配置频繁变更，页面稳定性不足，导致转化链路中断。",
          decision: "重构活动模板和配置协议，关键链路加入降级兜底与实时监控。",
          result: "大促期间链路稳定运行，转化提升且故障处理时长明显下降。",
        },
        {
          scenario: "中后台交付效率低",
          metric: "上线周期 -30%",
          challenge: "需求反复、模块耦合重，版本延期成为常态。",
          decision: "建立组件复用清单与交付准入机制，按业务域拆分模块边界。",
          result: "版本节奏稳定，跨团队协作成本下降，迭代吞吐明显提升。",
        },
        {
          scenario: "运营看板决策滞后",
          metric: "响应速度 +45%",
          challenge: "指标分散在多个系统，异常发现和定位依赖人工串联。",
          decision: "统一监控视图与告警分级，打通实时数据流和处置路径。",
          result: "运营团队可实时定位问题，决策响应速度和准确性同步提升。",
        },
      ],
    },
    capabilities: [
      {
        title: "产品体验与交互设计落地",
        summary: "关注信息层级、交互反馈与可达性，保证页面既专业又高效易用。",
        items: ["信息架构", "响应式布局", "微交互设计", "可访问性", "Design Token"],
      },
      {
        title: "前端架构与模块化治理",
        summary: "构建稳定的业务分层与组件边界，降低代码耦合与协作成本。",
        items: ["Vue / React", "状态管理", "组件抽象", "多端复用", "权限路由"],
      },
      {
        title: "工程化与研发效率提升",
        summary: "通过规范、脚手架、自动化发布提升团队研发一致性与可预测性。",
        items: ["Vite / Webpack", "CI/CD", "Lint / Commit 规范", "质量门禁", "自动化脚本"],
      },
      {
        title: "性能优化与可观测性",
        summary: "聚焦关键链路指标，持续治理首屏、交互响应与异常恢复能力。",
        items: ["包体积治理", "渲染性能", "缓存策略", "监控告警", "错误追踪"],
      },
    ],
    tooling: [
      {
        title: "语言与框架",
        items: ["TypeScript", "JavaScript ESNext", "Vue 2/3", "React 18", "Next.js", "Node.js"],
      },
      {
        title: "工程体系",
        items: ["Vite", "Webpack", "pnpm", "GitHub Actions", "Docker", "Nginx"],
      },
      {
        title: "质量与测试",
        items: ["ESLint", "Prettier", "Commitlint", "单测思维", "回归清单", "故障复盘"],
      },
      {
        title: "协作与管理",
        items: ["需求评审", "任务拆解", "跨团队协同", "风险识别", "文档沉淀", "知识共享"],
      },
    ],
    experiences: [
      {
        role: "前端开发工程师（前端组长）",
        company: "上海博为峰软件技术股份有限公司",
        period: "2021.02 — 2025.09",
        highlights: [
          "主导教育平台前端架构升级，完成多业务线模块化改造与规范统一。",
          "推动构建性能优化与 CDN 分层策略，核心资源消耗峰值下降 70%。",
          "建立需求评审与交付准入机制，降低返工率并提升版本发布稳定性。",
          "带领前端小组推进知识库与代码模板建设，提升团队整体交付效率。",
        ],
      },
      {
        role: "前端开发工程师",
        company: "上海费芮网络科技有限公司",
        period: "2019.03 — 2021.01",
        highlights: [
          "负责多个业务系统全周期开发，覆盖需求分析、实现、测试与上线支持。",
          "沉淀中后台高复用组件，形成表单、表格、审批流等标准化能力。",
          "通过页面渲染和数据请求治理，提升关键路径交互速度与稳定性。",
          "与产品、设计、测试建立高频协同机制，保障需求快速高质量落地。",
        ],
      },
      {
        role: "前端开发工程师",
        company: "蓝色起源企业管理（上海）有限公司",
        period: "2018.03 — 2019.03",
        highlights: [
          "参与定制化项目研发，负责前端技术选型与核心模块实现。",
          "将复杂需求抽象为可执行的前端方案，提高项目可交付性。",
          "优化跨团队协作流程，提升需求澄清效率和项目推进透明度。",
          "积累电商与企业应用场景经验，为后续复杂项目奠定方法基础。",
        ],
      },
    ],
    projectMeta: {
      roleLabel: "角色",
      scopeLabel: "我负责",
      stackLabel: "技术栈",
      challengeLabel: "业务挑战",
      strategyLabel: "实施策略",
      impactLabel: "影响指标",
      outcomeLabel: "项目结果",
    },
    projectToggle: {
      collapsedHint: "当前展示精选项目",
      expandedHint: "已展开全部项目",
      showMore: "查看更多项目",
      showLess: "收起项目",
      hiddenCountSuffix: "个",
    },
    projects: [
      {
        name: "学掌门网校 PC Web & App 商城",
        duration: "2021 — 2025",
        role: "前端负责人",
        scope: "负责核心交易链路架构、组件规范和性能治理策略。",
        stack: "Vue / TypeScript / Vite / Node.js",
        challenge: "多端业务规则复杂、活动页面迭代频繁，旧架构难以支撑快速上线。",
        strategy: "重构核心交易链路，统一组件协议与页面模板，引入监控看板持续追踪关键指标。",
        highlights: [
          "构建商城场景组件矩阵，覆盖商品、活动、支付、履约等核心流程。",
          "抽象公共业务逻辑，减少重复开发和跨端差异带来的维护成本。",
          "优化首屏加载与资源策略，提升高峰期活动页稳定性。",
        ],
        impact: ["首屏速度优化", "迭代效率提升", "线上稳定性增强"],
        outcome: "核心页面体验显著提升，活动大促期间系统稳定支撑高并发访问。",
      },
      {
        name: "企业中后台管理系统",
        duration: "2020 — 2023",
        role: "核心开发",
        scope: "负责权限模型、复杂表单组件和关键业务流程体验重构。",
        stack: "React / Ant Design / Zustand",
        challenge: "业务角色多、权限粒度细，复杂审批流程导致页面逻辑与状态管理膨胀。",
        strategy: "按领域拆分模块边界，建立权限路由模型与可复用业务组件，统一交互规范。",
        highlights: [
          "设计统一数据表格与筛选协议，降低同类页面重复建设成本。",
          "搭建可扩展权限控制层，支持角色快速新增与能力精细化管理。",
          "完善异常边界和日志追踪，缩短线上问题定位时间。",
        ],
        impact: ["复杂流程可用性提升", "权限管理可扩展", "故障定位效率提升"],
        outcome: "支撑多业务线并行迭代，复杂操作链路更加稳定清晰。",
      },
      {
        name: "协同工作台与数据大屏",
        duration: "2019 — 2022",
        role: "前端主程",
        scope: "负责实时渲染架构、图表性能优化与可视化规范统一。",
        stack: "Vue / ECharts / WebSocket",
        challenge: "实时数据刷新频率高，长时间运行易出现卡顿与内存增长问题。",
        strategy: "建立分层渲染策略与图表更新节流机制，统一可视化主题与组件生命周期管理。",
        highlights: [
          "实现大屏实时数据更新管线，保障关键指标展示时效性。",
          "统一图表主题与视觉规范，提升管理驾驶舱展示专业度。",
          "针对长时运行场景优化内存与重绘策略，降低卡顿风险。",
        ],
        impact: ["实时可视化稳定", "视觉一致性增强", "运行性能提升"],
        outcome: "支持业务侧实时监控与决策分析，系统长期运行稳定可靠。",
      },
      {
        name: "企业官网与品牌内容中台",
        duration: "2022 — 2024",
        role: "前端架构与体验负责人",
        scope: "负责内容中台组件抽象、模板策略和跨团队协同发布流程。",
        stack: "Next.js / TypeScript / Tailwind CSS",
        challenge: "品牌官网存在多团队并行更新、页面风格不一致和发布效率低的问题。",
        strategy: "构建可复用页面区块与内容模型，建立模板化发布流程并统一视觉组件规范。",
        highlights: [
          "搭建模块化页面构建能力，支持运营与品牌团队快速组合页面。",
          "沉淀统一组件样式和交互规范，降低设计与开发偏差。",
          "优化构建和发布链路，减少内容更新的人力成本与等待时间。",
        ],
        impact: ["品牌一致性提升", "内容上线提速", "协作成本降低"],
        outcome: "官网内容迭代节奏显著加快，品牌表达与转化路径更稳定。",
      },
      {
        name: "数据运营看板与告警中心",
        duration: "2023 — 2025",
        role: "核心前端开发",
        scope: "负责多源指标视图、告警处理闭环与高密度图表交互优化。",
        stack: "React / ECharts / WebSocket / Ant Design",
        challenge: "运营侧需要统一查看多系统指标并及时告警，但原有系统数据孤岛严重。",
        strategy: "重构指标视图层并接入实时数据通道，构建统一告警规则配置与分级展示能力。",
        highlights: [
          "实现多源数据聚合展示，支持按业务线快速切换和钻取分析。",
          "搭建告警分级与处理闭环，提升异常响应效率。",
          "优化复杂图表渲染性能，保障高密度数据场景下的交互流畅度。",
        ],
        impact: ["异常响应提速", "数据洞察增强", "跨系统监控统一"],
        outcome: "帮助运营团队形成统一监控视图，提升决策效率与问题处置速度。",
      },
    ],
    frontendShowcase: {
      eyebrow: "FRONTEND CRAFT",
      title: "前端专业能力可视化",
      description: "以真实工程指标与交付标准呈现前端专业性，不只展示界面，更展示体系化能力。",
      pillars: [
        {
          metric: "LCP ≤ 1.8s",
          title: "性能预算与渲染策略",
          detail: "围绕核心路径建立性能预算，持续治理首屏、交互与长列表渲染开销。",
          bullets: ["分路由代码拆分 + 关键资源优先级", "图片与字体加载策略优化", "渲染瓶颈定位与回归校验"],
        },
        {
          metric: "A11y 96+",
          title: "可访问性与设计一致性",
          detail: "将语义结构、键盘可达与视觉一致性纳入组件规范，降低后期补救成本。",
          bullets: ["语义化结构与焦点管理", "组件对比度与状态可读性", "设计 Token 与主题统一"],
        },
        {
          metric: "CI Pass 99%",
          title: "工程化质量门禁",
          detail: "通过类型检查、静态分析和自动化验证保证每次提交具备可发布质量。",
          bullets: ["TypeScript 严格类型约束", "Lint / Format / Test 自动检查", "灰度发布与回滚预案"],
        },
        {
          metric: "0 P1",
          title: "稳定性与可观测闭环",
          detail: "构建监控、告警、定位、复盘的稳定性闭环，保障核心流程长期可靠。",
          bullets: ["Web Vitals 与异常采集", "告警分级与响应值班机制", "发布后指标看护与复盘改进"],
        },
      ],
      labTitle: "Frontend Engineering Lab",
      labDescription: "工程化看板展示最近阶段的优化结果，体现从方案到落地的专业执行。",
      labMetrics: [
        {
          label: "Bundle 体积预算",
          value: "-42%",
          detail: "按路由拆分与依赖治理后，主包体积由 742KB 降到 430KB。",
          progress: "84%",
        },
        {
          label: "交互响应时间",
          value: "-38%",
          detail: "核心页面交互延迟从 210ms 收敛到 130ms。",
          progress: "76%",
        },
        {
          label: "线上异常恢复",
          value: "+55%",
          detail: "告警联动与错误分级后，平均恢复时长显著下降。",
          progress: "79%",
        },
      ],
      gatesLabel: "质量门禁",
      qualityGates: [
        "Type Safety Gate",
        "A11y Smoke Check",
        "Web Vitals Budget",
        "Visual Regression",
        "Release Checklist",
      ],
    },
    process: [
      {
        title: "1. 目标对齐",
        description: "明确业务目标、关键用户路径与成功指标，确保方向一致。",
      },
      {
        title: "2. 方案设计",
        description: "将需求拆解为信息结构、交互规则和技术实现路径。",
      },
      {
        title: "3. 工程执行",
        description: "通过模块边界、编码规范和自动化流程保障交付质量。",
      },
      {
        title: "4. 验证迭代",
        description: "上线后跟踪性能与业务指标，基于数据持续优化体验。",
      },
    ],
    contact: {
      phoneLabel: "电话",
      phone: "193 1863 8996",
      emailLabel: "邮箱",
      email: "leaolly333@163.com",
      locationLabel: "所在城市",
      location: "上海",
      availabilityLabel: "求职状态",
      availability: "可沟通新机会（高级前端 / 前端负责人）",
      responseLabel: "回复时效",
      response: "工作日 24 小时内",
      collaborationTitle: "合作方向",
      collaborationItems: [
        "复杂业务系统前端架构升级",
        "高品质官网 / 品牌页面开发",
        "组件库与设计系统建设",
        "性能治理与研发效率优化",
      ],
    },
    footer: "© 2026 李慧 · Delivering polished frontend experiences with engineering discipline.",
  },
  en: {
    brandName: "Li Hui",
    brandRole: "Senior Frontend Engineer",
    nav: [
      { href: "#about", label: "About" },
      { href: "#insight", label: "Insights" },
      { href: "#achievement", label: "Achievements" },
      { href: "#capability", label: "Capabilities" },
      { href: "#tooling", label: "Stack" },
      { href: "#experience", label: "Experience" },
      { href: "#projects", label: "Projects" },
      { href: "#process", label: "Workflow" },
      { href: "#contact", label: "Contact" },
    ],
    hero: {
      eyebrow: "PORTFOLIO 2026",
      title: "Delivering scalable frontend systems with design quality and engineering certainty",
      lead:
        "8+ years of frontend experience across education, e-commerce, collaboration tools, and enterprise applications. I turn complex requirements into clear interfaces, stable architectures, and measurable business outcomes.",
      primaryAction: "View Case Studies",
      secondaryAction: "Contact Me",
      badges: ["Vue / React", "Design System", "Performance", "Engineering Efficiency", "Cross-team"],
      sideTitle: "Design x Engineering",
      sideDescription:
        "I focus on product impact, developer productivity, and long-term maintainability—not just visual implementation.",
    },
    metrics: [
      { label: "Experience", value: "8+ Years" },
      { label: "Led Projects", value: "20+" },
      { label: "Cross-team Scope", value: "4+ Functions" },
      { label: "Resource Optimization", value: "Up to -70%" },
    ],
    sections: {
      insight: {
        eyebrow: "INSIGHTS",
        title: "Professional Perspective",
        description: "Clear problem framing, sustainable engineering practices, and consistent UX standards drive my work.",
      },
      achievement: {
        eyebrow: "ACHIEVEMENTS",
        title: "Key Outcomes",
        description: "Consistent, measurable improvements in speed, quality, and delivery reliability.",
      },
      capability: {
        eyebrow: "CAPABILITY",
        title: "Core Capability Matrix",
        description: "End-to-end delivery capability from user experience to engineering architecture.",
      },
      tooling: {
        eyebrow: "STACK",
        title: "Technical Depth & Practices",
        description: "Technology decisions are guided by maintainability, standardization, and observability.",
      },
      experience: {
        eyebrow: "EXPERIENCE",
        title: "Career Journey",
        description: "Built and validated execution frameworks in complex, high-demand business scenarios.",
      },
      projects: {
        eyebrow: "PROJECTS",
        title: "Representative Projects",
        description: "Each case is structured as challenge, strategy, and business outcome.",
      },
      process: {
        eyebrow: "WORKFLOW",
        title: "How I Work",
        description: "Outcome-driven collaboration model from discovery to measurable optimization.",
      },
      contact: {
        eyebrow: "CONTACT",
        title: "Collaboration",
        description: "Open to frontend leadership roles, consulting, and architecture optimization projects.",
      },
    },
    insight: {
      statement:
        "Great frontend work is not just about building screens—it is about aligning business goals, design language, and engineering systems for long-term product evolution.",
      nowTitle: "Current Focus",
      nowItems: [
        "Architecture modernization for complex business applications",
        "Scalable design-system implementation across teams",
        "Data-driven performance optimization loops",
      ],
      principleTitle: "Working Principles",
      principleItems: [
        "Frame the right problem before coding",
        "Design for reuse, not one-off delivery",
        "Validate improvements with measurable signals",
      ],
    },
    achievements: [
      {
        value: "-35%",
        label: "Average Delivery Cycle",
        detail: "Reduced end-to-end release lead time through requirement templates, component reuse, and release governance.",
      },
      {
        value: "70%",
        label: "Peak Resource Saving",
        detail: "Optimized build pipeline and static asset delivery strategy for lower infra and loading costs.",
      },
      {
        value: "99.9%",
        label: "Core Flow Stability",
        detail: "Improved runtime reliability with error categorization, observability, and recovery-oriented processes.",
      },
      {
        value: "1 System",
        label: "Design System Foundation",
        detail: "Built tokens, component rules, and page templates to unify language and reduce repeated implementation.",
      },
    ],
    businessShowcase: {
      eyebrow: "BUSINESS IMPACT",
      title: "Business Problem-Solving Capability",
      description:
        "I drive complex initiatives through a clear loop of problem framing, decision making, and measurable results.",
      anchors: [
        {
          label: "Lead Time to Release",
          value: "-35%",
          detail: "Requirement templates and priority discipline reduced cross-team waiting time.",
        },
        {
          label: "Core Flow Reliability",
          value: "99.9%",
          detail: "Release governance includes error tiers, canary rollout, and rollback playbooks.",
        },
        {
          label: "Cross-team Efficiency",
          value: "+40%",
          detail: "Unified planning language lowered communication overhead and rework.",
        },
      ],
      playbookTitle: "Execution Playbook",
      playbook: [
        {
          title: "1. Frame the Core Business Problem",
          description: "Identify the highest-impact bottlenecks for growth, conversion, or operational efficiency.",
          outcome: "Aligned goals, focused investments",
        },
        {
          title: "2. Turn Strategy into Executable Plan",
          description: "Break goals into deliverable modules with milestones, dependency mapping, and risk controls.",
          outcome: "Predictable delivery cadence",
        },
        {
          title: "3. Close the Loop with Metrics",
          description: "Validate impact post-release and iterate based on evidence, not intuition.",
          outcome: "Sustained, measurable outcomes",
        },
      ],
      casesTitle: "Business Case Breakdowns",
      cases: [
        {
          scenario: "Campaign Conversion Volatility",
          metric: "Conversion +22%",
          challenge: "Frequent campaign updates caused unstable pages and broken conversion paths.",
          decision: "Rebuilt campaign templates and config contracts, with runtime fallback and live monitoring.",
          result: "Conversion flow stayed stable during traffic peaks and incident handling time dropped significantly.",
        },
        {
          scenario: "Low Backoffice Delivery Throughput",
          metric: "Lead Time -30%",
          challenge: "Repeated requirement churn and tightly coupled modules slowed releases.",
          decision: "Introduced reusable component catalog and release entry criteria with domain-based boundaries.",
          result: "Version cadence stabilized and cross-team collaboration cost reduced with higher throughput.",
        },
        {
          scenario: "Delayed Operational Decisions",
          metric: "Response +45%",
          challenge: "Metrics were scattered across systems, and incident diagnosis relied on manual stitching.",
          decision: "Unified monitoring views and alert tiers with realtime data channels and response workflows.",
          result: "Ops teams identified issues faster with stronger decision speed and accuracy.",
        },
      ],
    },
    capabilities: [
      {
        title: "Product UX Execution",
        summary: "Deliver high-quality interaction and visual consistency with practical usability focus.",
        items: ["Information Architecture", "Responsive Layout", "Micro-interactions", "Accessibility", "Design Tokens"],
      },
      {
        title: "Frontend Architecture",
        summary: "Define clear module boundaries for scalable and maintainable product growth.",
        items: ["Vue / React", "State Management", "Component Abstraction", "Multi-platform Reuse", "Permission Routing"],
      },
      {
        title: "Engineering Productivity",
        summary: "Increase team delivery confidence through standards, toolchains, and automation.",
        items: ["Vite / Webpack", "CI/CD", "Code Standards", "Quality Gates", "Automation Scripts"],
      },
      {
        title: "Performance & Observability",
        summary: "Improve key-path performance and system reliability with data-driven optimization.",
        items: ["Bundle Strategy", "Rendering Performance", "Caching", "Monitoring", "Error Tracking"],
      },
    ],
    tooling: [
      {
        title: "Languages & Frameworks",
        items: ["TypeScript", "JavaScript ESNext", "Vue 2/3", "React 18", "Next.js", "Node.js"],
      },
      {
        title: "Engineering Infrastructure",
        items: ["Vite", "Webpack", "pnpm", "GitHub Actions", "Docker", "Nginx"],
      },
      {
        title: "Quality & Testing",
        items: ["ESLint", "Prettier", "Commitlint", "Testing Mindset", "Regression Checklist", "Postmortem"],
      },
      {
        title: "Collaboration & Delivery",
        items: ["Requirement Review", "Task Breakdown", "Cross-team Sync", "Risk Control", "Documentation", "Knowledge Sharing"],
      },
    ],
    experiences: [
      {
        role: "Frontend Engineer (Team Lead)",
        company: "Shanghai BoWeiFeng Software Technology Co., Ltd.",
        period: "Feb 2021 — Sep 2025",
        highlights: [
          "Led architecture refactoring for education platforms across multiple business lines.",
          "Delivered build and CDN optimization strategy with up to 70% resource reduction.",
          "Established delivery quality gates to reduce rework and release risks.",
          "Mentored team members with templates and shared engineering assets.",
        ],
      },
      {
        role: "Frontend Engineer",
        company: "Shanghai Feirui Network Technology Co., Ltd.",
        period: "Mar 2019 — Jan 2021",
        highlights: [
          "Shipped end-to-end product features from requirement to production.",
          "Built reusable admin components for tables, forms, and approval workflows.",
          "Improved render and request performance on key user paths.",
          "Collaborated closely with PM, design, and QA for reliable releases.",
        ],
      },
      {
        role: "Frontend Engineer",
        company: "Blue Origin Enterprise Management (Shanghai) Co., Ltd.",
        period: "Mar 2018 — Mar 2019",
        highlights: [
          "Implemented custom business systems with ownership of core frontend modules.",
          "Translated complex requirements into practical implementation plans.",
          "Improved collaboration transparency and delivery predictability.",
          "Built domain understanding in commerce and enterprise workflows.",
        ],
      },
    ],
    projectMeta: {
      roleLabel: "Role",
      scopeLabel: "My Scope",
      stackLabel: "Stack",
      challengeLabel: "Challenge",
      strategyLabel: "Strategy",
      impactLabel: "Impact",
      outcomeLabel: "Outcome",
    },
    projectToggle: {
      collapsedHint: "Showing selected projects",
      expandedHint: "Showing all projects",
      showMore: "Show more projects",
      showLess: "Show less",
      hiddenCountSuffix: "more",
    },
    projects: [
      {
        name: "XueZhangMen Web & App Commerce",
        duration: "2021 — 2025",
        role: "Frontend Lead",
        scope: "Owned core transaction architecture, component standards, and performance governance.",
        stack: "Vue / TypeScript / Vite / Node.js",
        challenge: "Rapid campaign iterations and multi-platform complexity were hard to scale with the previous architecture.",
        strategy: "Rebuilt core commerce flows, standardized component contracts, and introduced metrics dashboards.",
        highlights: [
          "Built a scenario-oriented component matrix for product, campaign, payment, and fulfillment flows.",
          "Abstracted shared logic for better reuse across platforms.",
          "Optimized loading and delivery strategy for campaign stability under traffic spikes.",
        ],
        impact: ["Faster first-screen", "Higher iteration speed", "Improved runtime stability"],
        outcome: "Achieved stable high-traffic campaign support with significantly better UX on core pages.",
      },
      {
        name: "Enterprise Admin Platform",
        duration: "2020 — 2023",
        role: "Core Engineer",
        scope: "Owned permission model design, complex form modules, and workflow UX restructuring.",
        stack: "React / Ant Design / Zustand",
        challenge: "Complex role-based workflows led to expanding state complexity and inconsistent interaction patterns.",
        strategy: "Separated domain modules, introduced permission routing models, and standardized reusable business components.",
        highlights: [
          "Created unified data-grid and filtering patterns to cut repetitive page implementation.",
          "Implemented extensible access control architecture.",
          "Improved issue traceability through error boundaries and logging strategy.",
        ],
        impact: ["Better usability", "Scalable permission model", "Faster issue diagnosis"],
        outcome: "Enabled parallel iteration across business teams with clearer and more reliable operation flows.",
      },
      {
        name: "Collaboration Console & Realtime Dashboard",
        duration: "2019 — 2022",
        role: "Lead Frontend Developer",
        scope: "Owned realtime rendering architecture, chart optimization, and visualization standards.",
        stack: "Vue / ECharts / WebSocket",
        challenge: "High-frequency realtime updates caused frame drops and memory growth in long-running sessions.",
        strategy: "Designed layered rendering and throttled chart updates, plus unified visualization lifecycle management.",
        highlights: [
          "Built realtime data pipelines for dashboard timeliness.",
          "Established visual standards for consistent large-screen reporting.",
          "Optimized memory and repaint behavior for long-duration operation.",
        ],
        impact: ["Stable realtime rendering", "Consistent visual language", "Improved long-run performance"],
        outcome: "Delivered a reliable realtime monitoring system for business decision support.",
      },
      {
        name: "Corporate Website & Brand Content Platform",
        duration: "2022 — 2024",
        role: "Frontend Architecture & Experience Lead",
        scope: "Owned content-block abstraction, template strategy, and multi-team publishing flow.",
        stack: "Next.js / TypeScript / Tailwind CSS",
        challenge: "The marketing site had inconsistent visual quality and slow updates across multiple collaborating teams.",
        strategy: "Built reusable page blocks and content models, then standardized design components with template-based publishing.",
        highlights: [
          "Delivered modular page composition for faster campaign and content updates.",
          "Aligned visual and interaction standards to reduce design-development drift.",
          "Streamlined build and release flow for lower operational effort.",
        ],
        impact: ["Better brand consistency", "Faster content launch", "Lower collaboration cost"],
        outcome: "The website iteration cadence improved significantly with stronger brand expression and clearer conversion paths.",
      },
      {
        name: "Operations Dashboard & Alert Center",
        duration: "2023 — 2025",
        role: "Core Frontend Engineer",
        scope: "Owned multi-source metrics views, alert handling loops, and dense chart interaction performance.",
        stack: "React / ECharts / WebSocket / Ant Design",
        challenge: "Operations teams needed unified real-time monitoring while data remained fragmented across systems.",
        strategy: "Rebuilt metrics visualization and connected realtime channels with configurable alert levels and workflows.",
        highlights: [
          "Integrated multi-source metrics into a unified operational view with drill-down support.",
          "Built alert-level handling loops to improve incident response.",
          "Optimized high-density chart rendering for smooth interactions under heavy data load.",
        ],
        impact: ["Faster incident response", "Stronger data insights", "Unified cross-system monitoring"],
        outcome: "Enabled teams to make faster decisions with a single reliable operational command view.",
      },
    ],
    frontendShowcase: {
      eyebrow: "FRONTEND CRAFT",
      title: "Frontend Professionalism Showcase",
      description:
        "Demonstrates frontend capability with engineering signals and delivery standards, not visuals alone.",
      pillars: [
        {
          metric: "LCP ≤ 1.8s",
          title: "Performance Budget & Rendering Strategy",
          detail: "Performance budget is defined on critical journeys and continuously improved for loading and interaction paths.",
          bullets: [
            "Route-level code splitting with priority tuning",
            "Image and font loading optimization",
            "Rendering bottleneck profiling and regression checks",
          ],
        },
        {
          metric: "A11y 96+",
          title: "Accessibility & Design Consistency",
          detail: "Semantic structure and keyboard accessibility are integrated into component standards from day one.",
          bullets: [
            "Semantic hierarchy and focus management",
            "Contrast and component state readability",
            "Tokenized theme and visual consistency",
          ],
        },
        {
          metric: "CI Pass 99%",
          title: "Engineering Quality Gates",
          detail: "Each change is validated with type checks and automation before release to keep delivery reliable.",
          bullets: [
            "Strict TypeScript contracts",
            "Automated lint, format, and tests",
            "Canary rollout and rollback plan",
          ],
        },
        {
          metric: "0 P1",
          title: "Reliability & Observability Loop",
          detail: "Monitoring, alerting, diagnosis, and postmortem processes are linked as one operating model.",
          bullets: [
            "Web Vitals and runtime error tracking",
            "Alert severity and response playbooks",
            "Post-release watch and optimization loops",
          ],
        },
      ],
      labTitle: "Frontend Engineering Lab",
      labDescription:
        "A compact dashboard of recent optimization outcomes that reflects execution quality from design to delivery.",
      labMetrics: [
        {
          label: "Bundle Budget",
          value: "-42%",
          detail: "Main bundle reduced from 742KB to 430KB via route splitting and dependency governance.",
          progress: "84%",
        },
        {
          label: "Interaction Latency",
          value: "-38%",
          detail: "Core user interactions improved from 210ms to 130ms average response time.",
          progress: "76%",
        },
        {
          label: "Incident Recovery",
          value: "+55%",
          detail: "Error categorization and alert workflow significantly reduced mean time to recovery.",
          progress: "79%",
        },
      ],
      gatesLabel: "Quality Gates",
      qualityGates: [
        "Type Safety Gate",
        "A11y Smoke Check",
        "Web Vitals Budget",
        "Visual Regression",
        "Release Checklist",
      ],
    },
    process: [
      {
        title: "1. Goal Alignment",
        description: "Clarify business goals, target journeys, and success metrics up front.",
      },
      {
        title: "2. Solution Design",
        description: "Translate requirements into information structure, interaction rules, and technical plans.",
      },
      {
        title: "3. Engineering Execution",
        description: "Ensure delivery quality with module boundaries, coding standards, and automation.",
      },
      {
        title: "4. Iterative Optimization",
        description: "Track performance and product metrics after release and optimize continuously.",
      },
    ],
    contact: {
      phoneLabel: "Phone",
      phone: "193 1863 8996",
      emailLabel: "Email",
      email: "leaolly333@163.com",
      locationLabel: "Location",
      location: "Shanghai",
      availabilityLabel: "Availability",
      availability: "Open to new opportunities (Senior Frontend / Frontend Lead)",
      responseLabel: "Response Time",
      response: "Within 24h on business days",
      collaborationTitle: "Collaboration Focus",
      collaborationItems: [
        "Frontend architecture for complex products",
        "Premium marketing / brand websites",
        "Design system and component platform",
        "Performance and engineering productivity optimization",
      ],
    },
    footer: "© 2026 Li Hui · Delivering polished frontend experiences with engineering discipline.",
  },
} as const;
